### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by controversial** [blacktop/atom-python-yapf#5]
I get this every time I try to format code. I've downloaded the yapf package to my main user directory, and these are my settings.

![screenshot 2015-07-15 11 01 52](https://cloud.githubusercontent.com/assets/10377391/8701622/ed3cf66a-2ae0-11e5-8e7e-1a39efeff964.png)

Here's the error report:

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [python-yapf](https://github.com/blacktop/atom-python-yapf) package, v0.7.0
### Stack Trace

Uncaught Error: spawn EACCES

```
At child_process.js:1145

Error: spawn EACCES
  at exports._errnoException (util.js:734:11)
  at ChildProcess.spawn (child_process.js:1145:11)
  at Object.exports.spawn (child_process.js:977:9)
  at PythonYAPF.module.exports.PythonYAPF.formatCode (/Users/luke/.atom/packages/python-yapf/lib/python-yapf.coffee:84:20)
  at atom-workspace.<anonymous> (/Users/luke/.atom/packages/python-yapf/lib/index.coffee:25:10)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```
### Commands

```
     -9:05.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -9:03.1.0 settings-view:open (atom-text-editor.editor.is-focused)
  4x -8:44.9.0 core:backspace (atom-text-editor#python-yapf.yapfStyle.editor.mini.is-focused)
     -8:11.1.0 python-yapf:formatCode (atom-text-editor.editor.is-focused)
     -8:05.7.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -8:05.7.0 core:cancel (atom-text-editor.editor.is-focused)
     -4:20.5.0 python-yapf:formatCode (atom-text-editor.editor.is-focused)
  3x -4:03.6.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:01.6.0 python-yapf:formatCode (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "*.pyc"
    ],
    "disabledPackages": [
      "deprecation-cop"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "python-yapf": {
    "yapfPath": "/Users/luke/yapf",
    "yapfStyle": "{based_on_style: google, column_limit:120}"
  }
}
```
### Installed Packages

``` coffee
# User
atom-material-syntax, v0.2.1
atom-material-ui, v0.5.1
color-picker, v2.0.9
minimap, v4.11.2
python-yapf, v0.7.0
script, v2.26.3

# Dev
No dev packages
```

**Comment by blacktop** [comment]
What version of yapf are you using?

**Comment by controversial** [comment]
0.2.2

**Comment by blacktop** [comment]
I am having trouble recreating this.  All my atom plugin does is run yapf.  So I don't understand how it can crash atom.  

Can you try updating Atom to 1.0.2 and yapf to 0.2.3 ?

I am using the same packages except `script, v2.26.3` can you try temporarily removing that or disabling that package?

Thank you for your help.

**Comment by controversial** [comment]
Sure, I'll try.

**Comment by blacktop** [comment]
I'm going to close this because I haven't heard back in a while.  Please feel free to re open if it is still broken.

**Comment by chrisdlangton** [comment]
Installed Atom and Yapf today both for the first time on this machine.
Ubuntu 16.04 LTS
uname -r
4.4.0-53-generic


**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Ubuntu 16.04.1
**Thrown From**: [python-yapf](https://github.com/blacktop/atom-python-yapf) package, v0.13.0


### Stack Trace

Uncaught Error: spawn EACCES

```
At internal/child_process.js:313

Error: spawn EACCES
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:392:9)
    at PythonYAPF.module.exports.PythonYAPF.runYapf (/home/chris/.atom/packages/python-yapf/lib/python-yapf.coffee:55:20)
    at PythonYAPF.module.exports.PythonYAPF.checkCode (/home/chris/.atom/packages/python-yapf/lib/python-yapf.coffee:29:6)
    at /home/chris/.atom/packages/python-yapf/lib/status-dialog.coffee:59:13
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /usr/share/atom/resources/app.asar/src/pane-container.js:348:27
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:288:22)
    at Pane.module.exports.Pane.activateItemAtIndex (/usr/share/atom/resources/app.asar/src/pane.js:420:19)
    at Pane.module.exports.Pane.activatePreviousItem (/usr/share/atom/resources/app.asar/src/pane.js:385:21)
    at Pane.module.exports.Pane.removeItem (/usr/share/atom/resources/app.asar/src/pane.js:570:16)
    at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app.asar/src/pane.js:643:16)
    at atom-tabs.TabBarView.onClick (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:711:17)
```

### Commands

```
     -9:25.4.0 core:copy (input.hidden-input)
  5x -6:55.7.0 core:move-left (input.hidden-input)
     -6:54.8.0 core:paste (input.hidden-input)
     -6:49.3.0 core:cancel (div.package-detail.panels-item)
     -2:25.9.0 core:copy (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-python"
    ],
    "openEmptyEditorOnStart": false,
    "telemetryConsent": "no"
  },
  "python-yapf": {
    "formatOnSave": true,
    "yapfPath": "/home/chris/.local/lib/python2.7/site-packages/yapf"
  }
}
```

### Installed Packages

```coffee
# User
atom-python-run, v0.6.2 (active)
autocomplete-python, v1.8.26 (active)
file-icons, v2.0.8 (active)
git-control, v0.8.2 (inactive)
git-controlhub, v0.3.0 (inactive)
git-diff-details, v1.4.0 (active)
git-log, v0.4.1 (active)
git-time-machine, v1.5.4 (inactive)
linter, v1.11.21 (active)
linter-python, v3.0.5 (inactive)
python-debugger, v0.1.0 (active)
python-indent, v1.0.0 (active)
python-tools, v0.6.8 (active)
python-yapf, v0.13.0 (active)
tree-view-git-status, v1.3.0 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by andrewinnocent** [comment]
I'm experiencing the same problem:

**Atom Version**: 1.29.0
**System**: Macbook OSX 10.13.6
**Thrown From**: python-yapf package, v0.14.0

Any solutions yet?
